import Head from 'next/head'
import Image from 'next/image'
import { ConfigProvider } from 'antd';
import { Search } from '../components/Search'
import { CoinsList } from '../components/CoinsList';
export default function Home() {
  return (
    <ConfigProvider direction="ltr">
      <div >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Search type="text" placeholder="جستجوی ارز" />
        <CoinsList />
      </div>
    </ConfigProvider>
  )
}

