import Head from 'next/head'
import Image from 'next/image'
import { ConfigProvider } from 'antd';
import { Search } from '../components/Search'
import {fetcher} from "../lib/fetcher"
import { CoinsList } from '../components/CoinsList';
export default function Home({dataList}) {
  return (
    <ConfigProvider direction="ltr">
      <div >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Search type="text" placeholder="جستجوی ارز" />
        <CoinsList dataList={dataList}/>
      </div>
    </ConfigProvider>
  )
}

export async function getStaticProps(params) {
  const dataList= await fetcher();
  return {
    props:{ dataList}
  }
}